package com.spfood.cms.intf.domain;

import javax.validation.constraints.Max;
import javax.validation.constraints.NotNull;

import com.spfood.kernel.domain.DomainObject;

public class Menu implements DomainObject {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.MenuCode
     *
     * @mbggenerated
     */
    private String menuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.name
     *
     * @mbggenerated
     */
    @NotNull
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.visualable
     *
     * @mbggenerated
     */
    private Integer visualable = 0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.display_order
     *
     * @mbggenerated
     */
	@Max(value=100)
    private Integer displayOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.parent
     *
     * @mbggenerated
     */
    private String parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.commodity_code
     *
     * @mbggenerated
     */
    private String commodityCode;
    
	/**
     * 图片地址 
     */
    private String imageUrl;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.MenuCode
     *
     * @return the value of menu.MenuCode
     *
     * @mbggenerated
     */
    public String getMenuCode() {
        return menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.MenuCode
     *
     * @param menuCode the value for menu.MenuCode
     *
     * @mbggenerated
     */
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode == null ? null : menuCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.name
     *
     * @return the value of menu.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.name
     *
     * @param name the value for menu.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.visualable
     *
     * @return the value of menu.visualable
     *
     * @mbggenerated
     */
    public Integer getVisualable() {
        return visualable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.visualable
     *
     * @param visualable the value for menu.visualable
     *
     * @mbggenerated
     */
    public void setVisualable(Integer visualable) {
        this.visualable = visualable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.display_order
     *
     * @return the value of menu.display_order
     *
     * @mbggenerated
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.display_order
     *
     * @param displayOrder the value for menu.display_order
     *
     * @mbggenerated
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.parent
     *
     * @return the value of menu.parent
     *
     * @mbggenerated
     */
    public String getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.parent
     *
     * @param parent the value for menu.parent
     *
     * @mbggenerated
     */
    public void setParent(String parent) {
        this.parent = parent == null ? null : parent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.commodity_code
     *
     * @return the value of menu.commodity_code
     *
     * @mbggenerated
     */
    public String getCommodityCode() {
        return commodityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.commodity_code
     *
     * @param commodityCode the value for menu.commodity_code
     *
     * @mbggenerated
     */
    public void setCommodityCode(String commodityCode) {
        this.commodityCode = commodityCode == null ? null : commodityCode.trim();
    }
    
    public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}
}