package com.spfood.cms.intf.domain;


import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.spfood.kernel.domain.DomainObject;

public class SearchKeyword implements DomainObject {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_keyword.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_keyword.keyword
     *
     * @mbggenerated
     */
    @Size(max=40,min=0)
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_keyword.is_default
     *
     * @mbggenerated
     */
    @NotNull
    private Boolean isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_keyword.display_order
     *
     * @mbggenerated
     */
    @NotNull
    private Integer displayOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_keyword.ID
     *
     * @return the value of search_keyword.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_keyword.ID
     *
     * @param iD the value for search_keyword.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_keyword.keyword
     *
     * @return the value of search_keyword.keyword
     *
     * @mbggenerated
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_keyword.keyword
     *
     * @param keyword the value for search_keyword.keyword
     *
     * @mbggenerated
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_keyword.is_default
     *
     * @return the value of search_keyword.is_default
     *
     * @mbggenerated
     */
    public Boolean getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_keyword.is_default
     *
     * @param isDefault the value for search_keyword.is_default
     *
     * @mbggenerated
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_keyword.display_order
     *
     * @return the value of search_keyword.display_order
     *
     * @mbggenerated
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_keyword.display_order
     *
     * @param displayOrder the value for search_keyword.display_order
     *
     * @mbggenerated
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }
}