package com.spfood.pms.intf.domain;

import com.spfood.kernel.domain.DomainObject;

public class CommodityCommentPicture implements DomainObject {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity_comment_picture.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity_comment_picture.orderno
     *
     * @mbggenerated
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity_comment_picture.commoditycode
     *
     * @mbggenerated
     */
    private String commoditycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity_comment_picture.picture_url
     *
     * @mbggenerated
     */
    private String pictureUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity_comment_picture.display_order
     *
     * @mbggenerated
     */
    private Integer displayOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity_comment_picture.id
     *
     * @return the value of pms_commodity_comment_picture.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity_comment_picture.id
     *
     * @param id the value for pms_commodity_comment_picture.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity_comment_picture.orderno
     *
     * @return the value of pms_commodity_comment_picture.orderno
     *
     * @mbggenerated
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity_comment_picture.orderno
     *
     * @param orderno the value for pms_commodity_comment_picture.orderno
     *
     * @mbggenerated
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno == null ? null : orderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity_comment_picture.commoditycode
     *
     * @return the value of pms_commodity_comment_picture.commoditycode
     *
     * @mbggenerated
     */
    public String getCommoditycode() {
        return commoditycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity_comment_picture.commoditycode
     *
     * @param commoditycode the value for pms_commodity_comment_picture.commoditycode
     *
     * @mbggenerated
     */
    public void setCommoditycode(String commoditycode) {
        this.commoditycode = commoditycode == null ? null : commoditycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity_comment_picture.picture_url
     *
     * @return the value of pms_commodity_comment_picture.picture_url
     *
     * @mbggenerated
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity_comment_picture.picture_url
     *
     * @param pictureUrl the value for pms_commodity_comment_picture.picture_url
     *
     * @mbggenerated
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl == null ? null : pictureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity_comment_picture.display_order
     *
     * @return the value of pms_commodity_comment_picture.display_order
     *
     * @mbggenerated
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity_comment_picture.display_order
     *
     * @param displayOrder the value for pms_commodity_comment_picture.display_order
     *
     * @mbggenerated
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }
}