package com.spfood.pms.intf.domain;

import com.spfood.kernel.domain.DomainObject;

public class CommodityProperty implements DomainObject {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity_property.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity_property.commdity_code
     *
     * @mbggenerated
     */
    private Commodity commodity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity_property.commdity_property_name
     *
     * @mbggenerated
     */
    private String commdityPropertyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity_property.commdity_property_value
     *
     * @mbggenerated
     */
    private String commdityPropertyValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity_property.id
     *
     * @return the value of pms_commodity_property.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity_property.id
     *
     * @param id the value for pms_commodity_property.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity_property.commdity_property_name
     *
     * @return the value of pms_commodity_property.commdity_property_name
     *
     * @mbggenerated
     */
    public String getCommdityPropertyName() {
        return commdityPropertyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity_property.commdity_property_name
     *
     * @param commdityPropertyName the value for pms_commodity_property.commdity_property_name
     *
     * @mbggenerated
     */
    public void setCommdityPropertyName(String commdityPropertyName) {
        this.commdityPropertyName = commdityPropertyName == null ? null : commdityPropertyName.trim();
    }

    public Commodity getCommodity() {
		return commodity;
	}

	public void setCommodity(Commodity commodity) {
		this.commodity = commodity;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity_property.commdity_property_value
     *
     * @return the value of pms_commodity_property.commdity_property_value
     *
     * @mbggenerated
     */
    public String getCommdityPropertyValue() {
        return commdityPropertyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity_property.commdity_property_value
     *
     * @param commdityPropertyValue the value for pms_commodity_property.commdity_property_value
     *
     * @mbggenerated
     */
    public void setCommdityPropertyValue(String commdityPropertyValue) {
        this.commdityPropertyValue = commdityPropertyValue == null ? null : commdityPropertyValue.trim();
    }
}