package com.spfood.pms.intf.domain;

import com.spfood.kernel.domain.DomainObject;

public class CommodityCommentType implements DomainObject {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity_comment_type.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity_comment_type.comment_type_code
     *
     * @mbggenerated
     */
    private Integer commentTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity_comment_type.comment_type_name
     *
     * @mbggenerated
     */
    private String commentTypeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity_comment_type.id
     *
     * @return the value of pms_commodity_comment_type.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity_comment_type.id
     *
     * @param id the value for pms_commodity_comment_type.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity_comment_type.comment_type_code
     *
     * @return the value of pms_commodity_comment_type.comment_type_code
     *
     * @mbggenerated
     */
    public Integer getCommentTypeCode() {
        return commentTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity_comment_type.comment_type_code
     *
     * @param commentTypeCode the value for pms_commodity_comment_type.comment_type_code
     *
     * @mbggenerated
     */
    public void setCommentTypeCode(Integer commentTypeCode) {
        this.commentTypeCode = commentTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity_comment_type.comment_type_name
     *
     * @return the value of pms_commodity_comment_type.comment_type_name
     *
     * @mbggenerated
     */
    public String getCommentTypeName() {
        return commentTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity_comment_type.comment_type_name
     *
     * @param commentTypeName the value for pms_commodity_comment_type.comment_type_name
     *
     * @mbggenerated
     */
    public void setCommentTypeName(String commentTypeName) {
        this.commentTypeName = commentTypeName == null ? null : commentTypeName.trim();
    }
}