package com.spfood.pms.intf.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.spfood.kernel.domain.DomainObject;

import java.util.Calendar;
import java.util.Date;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;

public class CommodityComment implements DomainObject {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity_comment.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity_comment.comment_usercode
     *
     * @mbggenerated
     */
    private String commentUsercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity_comment.commodity_code
     *
     * @mbggenerated
     */
    private String commodityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity_comment.category_code
     *
     * @mbggenerated
     */
    private String categoryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity_comment.comment_content
     *
     * @mbggenerated
     */
    private String commentContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity_comment.comment_grade
     *
     * @mbggenerated
     */
    private Integer commentGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity_comment.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity_comment.comment_time
     *
     * @mbggenerated
     */
    private Date commentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity_comment.comment_status
     *
     * @mbggenerated
     */
    private Integer commentStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity_comment.comment_type_code
     *
     * @mbggenerated
     */
    private Integer commentTypeCode;

    

    /** @pdOid 1f106d31-e70e-410f-8e6c-fb14f02ab93e */
    private int expressGrade;
    /** @pdOid 37f64c54-6d93-47e9-9a0a-3c26adf630d4 */
    private int packageGrade;
    /** @pdOid 4784beb9-770b-4774-a525-0fd60fe3835e */
    private int commodityGrade;
    /** @pdOid 044f923a-98cb-4128-8bb2-e246991b808e */
    private int expressGoodCount;
    /** @pdOid 76ff4349-349b-46fe-9e9c-d0a38ea2c8b0 */
    private int expressMidCount;
    /** @pdOid 89a19097-c46c-4e43-9844-4646c3fd106a */
    private int expressBadCount;
    /** @pdOid 928a6623-b6c6-4a60-b35f-3d974ca8ad29 */
    private int packageGoodCount;
    /** @pdOid bb8cd62f-4d5c-4698-ad44-f3f6291125fd */
    private int packageMidCount;
    /** @pdOid e1741efd-fddf-42c5-bff9-b2d82db3bc9f */
    private int packageBadCount;
    /** @pdOid a03279e2-798f-437f-b0d3-24cc84cffacc */
    private int commodityGoodCount;
    /** @pdOid a0f4df2f-b922-4141-a3bc-c86cb35d5a99 */
    private int commodityMidCount;
    /** @pdOid 0356ae5e-337f-4a1d-9936-96f7cc64425c */
    private int commodityBadCount;
    /** @pdOid aa0335f8-fa66-45ab-9c5f-1b3e77ccd426 */
    private int orderBy;//排序
    private int subStringSize;//品类用，左连接截取品类code位数
    private int CommodityCommentLevel;//商品检索评论等级
    private Date CommodityCommentDateSt;//商品检索评论开始时间
    private Date CommodityCommentDateEd;//商品检索评论结束时间
    private List<Long> idList;//idList
    private List<String> commentUsercodeList;//拥护编码List
    private String commentUserTel;//拥护电话
    
    private List<CommodityCommentPicture> CommodityCommentPictures;
    
    /**
	 * @return the subStringSize
	 */
	public int getSubStringSize() {
		return subStringSize;
	}

	/**
	 * @param subStringSize the subStringSize to set
	 */
	public void setSubStringSize(int subStringSize) {
		this.subStringSize = subStringSize;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity_comment.id
     *
     * @return the value of pms_commodity_comment.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity_comment.id
     *
     * @param id the value for pms_commodity_comment.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity_comment.comment_usercode
     *
     * @return the value of pms_commodity_comment.comment_usercode
     *
     * @mbggenerated
     */
    public String getCommentUsercode() {
        return commentUsercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity_comment.comment_usercode
     *
     * @param commentUsercode the value for pms_commodity_comment.comment_usercode
     *
     * @mbggenerated
     */
    public void setCommentUsercode(String commentUsercode) {
        this.commentUsercode = commentUsercode == null ? null : commentUsercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity_comment.commodity_code
     *
     * @return the value of pms_commodity_comment.commodity_code
     *
     * @mbggenerated
     */
    public String getCommodityCode() {
        return commodityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity_comment.commodity_code
     *
     * @param commodityCode the value for pms_commodity_comment.commodity_code
     *
     * @mbggenerated
     */
    public void setCommodityCode(String commodityCode) {
        this.commodityCode = commodityCode == null ? null : commodityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity_comment.category_code
     *
     * @return the value of pms_commodity_comment.category_code
     *
     * @mbggenerated
     */
    public String getCategoryCode() {
        return categoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity_comment.category_code
     *
     * @param categoryCode the value for pms_commodity_comment.category_code
     *
     * @mbggenerated
     */
    public void setCategoryCode(String categoryCode) {
        this.categoryCode = categoryCode == null ? null : categoryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity_comment.comment_content
     *
     * @return the value of pms_commodity_comment.comment_content
     *
     * @mbggenerated
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity_comment.comment_content
     *
     * @param commentContent the value for pms_commodity_comment.comment_content
     *
     * @mbggenerated
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity_comment.comment_grade
     *
     * @return the value of pms_commodity_comment.comment_grade
     *
     * @mbggenerated
     */
    public Integer getCommentGrade() {
        return commentGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity_comment.comment_grade
     *
     * @param commentGrade the value for pms_commodity_comment.comment_grade
     *
     * @mbggenerated
     */
    public void setCommentGrade(Integer commentGrade) {
        this.commentGrade = commentGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity_comment.order_no
     *
     * @return the value of pms_commodity_comment.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity_comment.order_no
     *
     * @param orderNo the value for pms_commodity_comment.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity_comment.comment_time
     *
     * @return the value of pms_commodity_comment.comment_time
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    public Date getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity_comment.comment_time
     *
     * @param commentTime the value for pms_commodity_comment.comment_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    public void setCommentTime(Date commentTime) {
        this.commentTime = commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity_comment.comment_status
     *
     * @return the value of pms_commodity_comment.comment_status
     *
     * @mbggenerated
     */
    public Integer getCommentStatus() {
        return commentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity_comment.comment_status
     *
     * @param commentStatus the value for pms_commodity_comment.comment_status
     *
     * @mbggenerated
     */
    public void setCommentStatus(Integer commentStatus) {
        this.commentStatus = commentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity_comment.comment_type_code
     *
     * @return the value of pms_commodity_comment.comment_type_code
     *
     * @mbggenerated
     */
    public Integer getCommentTypeCode() {
        return commentTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity_comment.comment_type_code
     *
     * @param commentTypeCode the value for pms_commodity_comment.comment_type_code
     *
     * @mbggenerated
     */
    public void setCommentTypeCode(Integer commentTypeCode) {
        this.commentTypeCode = commentTypeCode;
    }

	/**
	 * @return the expressGrade
	 */
	public int getExpressGrade() {
		return expressGrade;
	}

	/**
	 * @param expressGrade the expressGrade to set
	 */
	public void setExpressGrade(int expressGrade) {
		this.expressGrade = expressGrade;
	}

	/**
	 * @return the packageGrade
	 */
	public int getPackageGrade() {
		return packageGrade;
	}

	/**
	 * @param packageGrade the packageGrade to set
	 */
	public void setPackageGrade(int packageGrade) {
		this.packageGrade = packageGrade;
	}

	/**
	 * @return the commodityGrade
	 */
	public int getCommodityGrade() {
		return commodityGrade;
	}

	/**
	 * @param commodityGrade the commodityGrade to set
	 */
	public void setCommodityGrade(int commodityGrade) {
		this.commodityGrade = commodityGrade;
	}

	/**
	 * @return the expressGoodCount
	 */
	public int getExpressGoodCount() {
		return expressGoodCount;
	}

	/**
	 * @param expressGoodCount the expressGoodCount to set
	 */
	public void setExpressGoodCount(int expressGoodCount) {
		this.expressGoodCount = expressGoodCount;
	}

	/**
	 * @return the expressMidCount
	 */
	public int getExpressMidCount() {
		return expressMidCount;
	}

	/**
	 * @param expressMidCount the expressMidCount to set
	 */
	public void setExpressMidCount(int expressMidCount) {
		this.expressMidCount = expressMidCount;
	}

	/**
	 * @return the expressBadCount
	 */
	public int getExpressBadCount() {
		return expressBadCount;
	}

	/**
	 * @param expressBadCount the expressBadCount to set
	 */
	public void setExpressBadCount(int expressBadCount) {
		this.expressBadCount = expressBadCount;
	}

	/**
	 * @return the packageGoodCount
	 */
	public int getPackageGoodCount() {
		return packageGoodCount;
	}

	/**
	 * @param packageGoodCount the packageGoodCount to set
	 */
	public void setPackageGoodCount(int packageGoodCount) {
		this.packageGoodCount = packageGoodCount;
	}

	/**
	 * @return the packageMidCount
	 */
	public int getPackageMidCount() {
		return packageMidCount;
	}

	/**
	 * @param packageMidCount the packageMidCount to set
	 */
	public void setPackageMidCount(int packageMidCount) {
		this.packageMidCount = packageMidCount;
	}

	/**
	 * @return the packageBadCount
	 */
	public int getPackageBadCount() {
		return packageBadCount;
	}

	/**
	 * @param packageBadCount the packageBadCount to set
	 */
	public void setPackageBadCount(int packageBadCount) {
		this.packageBadCount = packageBadCount;
	}

	/**
	 * @return the commodityGoodCount
	 */
	public int getCommodityGoodCount() {
		return commodityGoodCount;
	}

	/**
	 * @param commodityGoodCount the commodityGoodCount to set
	 */
	public void setCommodityGoodCount(int commodityGoodCount) {
		this.commodityGoodCount = commodityGoodCount;
	}

	/**
	 * @return the commodityMidCount
	 */
	public int getCommodityMidCount() {
		return commodityMidCount;
	}

	/**
	 * @param commodityMidCount the commodityMidCount to set
	 */
	public void setCommodityMidCount(int commodityMidCount) {
		this.commodityMidCount = commodityMidCount;
	}

	/**
	 * @return the commodityBadCount
	 */
	public int getCommodityBadCount() {
		return commodityBadCount;
	}

	/**
	 * @param commodityBadCount the commodityBadCount to set
	 */
	public void setCommodityBadCount(int commodityBadCount) {
		this.commodityBadCount = commodityBadCount;
	}

	/**
	 * @return the orderBy
	 */
	public int getOrderBy() {
		return orderBy;
	}

	/**
	 * @param orderBy the orderBy to set
	 */
	public void setOrderBy(int orderBy) {
		this.orderBy = orderBy;
	}

	/**
	 * @return the commodityCommentLevel
	 */
	public int getCommodityCommentLevel() {
		return CommodityCommentLevel;
	}

	/**
	 * @param commodityCommentLevel the commodityCommentLevel to set
	 */
	public void setCommodityCommentLevel(int commodityCommentLevel) {
		CommodityCommentLevel = commodityCommentLevel;
	}

	/**
	 * @return the commodityCommentDateSt
	 */
	@JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
	public Date getCommodityCommentDateSt() {
		return CommodityCommentDateSt;
	}

	/**
	 * @param commodityCommentDateSt the commodityCommentDateSt to set
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	public void setCommodityCommentDateSt(Date commodityCommentDateSt) {
		CommodityCommentDateSt = commodityCommentDateSt;
	}

	/**
	 * @return the commodityCommentDateEd
	 */
	@JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
	public Date getCommodityCommentDateEd() {
		return CommodityCommentDateEd;
	}

	/**
	 * @param commodityCommentDateEd the commodityCommentDateEd to set
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	public void setCommodityCommentDateEd(Date commodityCommentDateEd) {
		if (commodityCommentDateEd != null) {
			Calendar calendar = Calendar.getInstance();
			calendar.setTime(commodityCommentDateEd); 
			calendar.set(Calendar.DATE,calendar.get(Calendar.DATE)+1);
			CommodityCommentDateEd = calendar.getTime();
		}else {
			CommodityCommentDateEd = commodityCommentDateEd;
		}
	}

	/**
	 * @return the idList
	 */
	public List<Long> getIdList() {
		return idList;
	}

	/**
	 * @param idList the idList to set
	 */
	public void setIdList(List<Long> idList) {
		this.idList = idList;
	}

	/**
	 * @return the commentUsercodeList
	 */
	public List<String> getCommentUsercodeList() {
		return commentUsercodeList;
	}

	/**
	 * @param commentUsercodeList the commentUsercodeList to set
	 */
	public void setCommentUsercodeList(List<String> commentUsercodeList) {
		this.commentUsercodeList = commentUsercodeList;
	}

	/**
	 * @return the commentUserTel
	 */
	public String getCommentUserTel() {
		return commentUserTel;
	}

	/**
	 * @param commentUserTel the commentUserTel to set
	 */
	public void setCommentUserTel(String commentUserTel) {
		this.commentUserTel = commentUserTel;
	}

	/**
	 * @return the commodityCommentPictures
	 */
	public List<CommodityCommentPicture> getCommodityCommentPictures() {
		return CommodityCommentPictures;
	}

	/**
	 * @param commodityCommentPictures the commodityCommentPictures to set
	 */
	public void setCommodityCommentPictures(List<CommodityCommentPicture> commodityCommentPictures) {
		CommodityCommentPictures = commodityCommentPictures;
	}
}