package com.spfood.pms.intf.domain;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import com.spfood.kernel.domain.DomainObject;

public class Commodity implements DomainObject {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity.commodity_code
     *
     * @mbggenerated
     */
    private String commodityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity.commodity_gs1_code
     *
     * @mbggenerated
     */
    private String commodityGs1Code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity.category_code
     *
     * @mbggenerated
     */
    private ProductCategory category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity.product_code
     *
     * @mbggenerated
     */
    private Product product;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity.commodity_name
     *
     * @mbggenerated
     */
    private String commodityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity.commodity_show_name
     *
     * @mbggenerated
     */
    private String commodityShowName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity.commodity_price
     *
     * @mbggenerated
     */
    private BigDecimal commodityPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity.commodity_sales_price
     *
     * @mbggenerated
     */
    private BigDecimal commoditySalesPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity.sales_amount
     *
     * @mbggenerated
     */
    private Integer salesAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity.default_flag
     *
     * @mbggenerated
     */
    private Integer defaultFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity.commodity_quantity
     *
     * @mbggenerated
     */
    private Integer commodityQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity.commodity_status
     *0-待审核,1-已通过审核,2-未通过审核,3-上架,4-下架,5-停用
     * @mbggenerated
     */
    private Integer commodityStatus;
    
    /**
     * 产品数量
     */
    private BigDecimal commodityProductQuantity;
    
    /**
     * 商品重量
     */
    private Double commodityWeight;
    
    /**
     * 商品重量单位
     */
    private String commodityWeightUnit;
    
    /**
     * 商品显示端（小B端，C端）
     */
    private String commodityShowPlace;
    
    /**
     * 可送达区域
     */
    private String commodityCity;
    
    /**
     * 商品说明
     */
    private String commodityComment;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity.last_update_date
     *
     * @mbggenerated
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity.last_update_user
     *
     * @mbggenerated
     */
    private String lastUpdateUser;
    
    /**
     * 商品属性
     */
    private String searchProperty;
    
    /**
     * 商品默认图片
     */
    private String imageUrl;
    
    /**
     * 属性集合
     */
    private List<CommodityProperty> commodityPropertys;
    
    /**
     * 图片集合
     */
    private List<CommodityPicture> commodityPictures;
	/**
	 * 商品评论
	 */
	private CommodityComment commodityCommentDomain;
	/**
     * 税率名称
     */
    private String taxRateName;
    
    /**
     * 税率值
     */
    private String taxRateValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity.id
     *
     * @return the value of pms_commodity.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity.id
     *
     * @param id the value for pms_commodity.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity.commodity_code
     *
     * @return the value of pms_commodity.commodity_code
     *
     * @mbggenerated
     */
    public String getCommodityCode() {
        return commodityCode;
    }

    public List<CommodityProperty> getCommodityPropertys() {
		return commodityPropertys;
	}

	public void setCommodityPropertys(List<CommodityProperty> commodityPropertys) {
		this.commodityPropertys = commodityPropertys;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity.commodity_code
     *
     * @param commodityCode the value for pms_commodity.commodity_code
     *
     * @mbggenerated
     */
    public void setCommodityCode(String commodityCode) {
        this.commodityCode = commodityCode == null ? null : commodityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity.commodity_gs1_code
     *
     * @return the value of pms_commodity.commodity_gs1_code
     *
     * @mbggenerated
     */
    public String getCommodityGs1Code() {
        return commodityGs1Code;
    }

    public String getCommodityShowPlace() {
		return commodityShowPlace;
	}

	public String getCommodityComment() {
		return commodityComment;
	}

	public void setCommodityComment(String commodityComment) {
		this.commodityComment = commodityComment;
	}

	public void setCommodityShowPlace(String commodityShowPlace) {
		this.commodityShowPlace = commodityShowPlace;
	}

	public String getCommodityCity() {
		return commodityCity;
	}

	public void setCommodityCity(String commodityCity) {
		this.commodityCity = commodityCity;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity.commodity_gs1_code
     *
     * @param commodityGs1Code the value for pms_commodity.commodity_gs1_code
     *
     * @mbggenerated
     */
    public void setCommodityGs1Code(String commodityGs1Code) {
        this.commodityGs1Code = commodityGs1Code == null ? null : commodityGs1Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity.commodity_name
     *
     * @return the value of pms_commodity.commodity_name
     *
     * @mbggenerated
     */
    public String getCommodityName() {
        return commodityName;
    }

    public ProductCategory getCategory() {
		return category;
	}

	public BigDecimal getCommodityProductQuantity() {
		return commodityProductQuantity;
	}

	public void setCommodityProductQuantity(BigDecimal commodityProductQuantity) {
		this.commodityProductQuantity = commodityProductQuantity;
	}

	public List<CommodityPicture> getCommodityPictures() {
		return commodityPictures;
	}

	public void setCommodityPictures(List<CommodityPicture> commodityPictures) {
		this.commodityPictures = commodityPictures;
	}

	public void setCategory(ProductCategory category) {
		this.category = category;
	}

	public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity.commodity_name
     *
     * @param commodityName the value for pms_commodity.commodity_name
     *
     * @mbggenerated
     */
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName == null ? null : commodityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity.commodity_show_name
     *
     * @return the value of pms_commodity.commodity_show_name
     *
     * @mbggenerated
     */
    public String getCommodityShowName() {
        return commodityShowName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity.commodity_show_name
     *
     * @param commodityShowName the value for pms_commodity.commodity_show_name
     *
     * @mbggenerated
     */
    public void setCommodityShowName(String commodityShowName) {
        this.commodityShowName = commodityShowName == null ? null : commodityShowName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity.commodity_price
     *
     * @return the value of pms_commodity.commodity_price
     *
     * @mbggenerated
     */
    public BigDecimal getCommodityPrice() {
        return commodityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity.commodity_price
     *
     * @param commodityPrice the value for pms_commodity.commodity_price
     *
     * @mbggenerated
     */
    public void setCommodityPrice(BigDecimal commodityPrice) {
        this.commodityPrice = commodityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity.commodity_sales_price
     *
     * @return the value of pms_commodity.commodity_sales_price
     *
     * @mbggenerated
     */
    public BigDecimal getCommoditySalesPrice() {
        return commoditySalesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity.commodity_sales_price
     *
     * @param commoditySalesPrice the value for pms_commodity.commodity_sales_price
     *
     * @mbggenerated
     */
    public void setCommoditySalesPrice(BigDecimal commoditySalesPrice) {
        this.commoditySalesPrice = commoditySalesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity.sales_amount
     *
     * @return the value of pms_commodity.sales_amount
     *
     * @mbggenerated
     */
    public Integer getSalesAmount() {
        return salesAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity.sales_amount
     *
     * @param salesAmount the value for pms_commodity.sales_amount
     *
     * @mbggenerated
     */
    public void setSalesAmount(Integer salesAmount) {
        this.salesAmount = salesAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity.default_flag
     *
     * @return the value of pms_commodity.default_flag
     *
     * @mbggenerated
     */
    public Integer getDefaultFlag() {
        return defaultFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity.default_flag
     *
     * @param defaultFlag the value for pms_commodity.default_flag
     *
     * @mbggenerated
     */
    public void setDefaultFlag(Integer defaultFlag) {
        this.defaultFlag = defaultFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity.commodity_quantity
     *
     * @return the value of pms_commodity.commodity_quantity
     *
     * @mbggenerated
     */
    public Integer getCommodityQuantity() {
        return commodityQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity.commodity_quantity
     *
     * @param commodityQuantity the value for pms_commodity.commodity_quantity
     *
     * @mbggenerated
     */
    public void setCommodityQuantity(Integer commodityQuantity) {
        this.commodityQuantity = commodityQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity.commodity_status
     *
     * @return the value of pms_commodity.commodity_status
     *
     * @mbggenerated
     */
    public Integer getCommodityStatus() {
        return commodityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity.commodity_status
     *
     * @param commodityStatus the value for pms_commodity.commodity_status
     *
     * @mbggenerated
     */
    public void setCommodityStatus(Integer commodityStatus) {
        this.commodityStatus = commodityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity.create_date
     *
     * @return the value of pms_commodity.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity.create_date
     *
     * @param createDate the value for pms_commodity.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getSearchProperty() {
		return searchProperty;
	}

	public void setSearchProperty(String searchProperty) {
		this.searchProperty = searchProperty;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity.create_user
     *
     * @return the value of pms_commodity.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity.create_user
     *
     * @param createUser the value for pms_commodity.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity.last_update_date
     *
     * @return the value of pms_commodity.last_update_date
     *
     * @mbggenerated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity.last_update_date
     *
     * @param lastUpdateDate the value for pms_commodity.last_update_date
     *
     * @mbggenerated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    public Double getCommodityWeight() {
		return commodityWeight;
	}

	public void setCommodityWeight(Double commodityWeight) {
		this.commodityWeight = commodityWeight;
	}

	public String getCommodityWeightUnit() {
		return commodityWeightUnit;
	}

	public void setCommodityWeightUnit(String commodityWeightUnit) {
		this.commodityWeightUnit = commodityWeightUnit;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity.last_update_user
     *
     * @return the value of pms_commodity.last_update_user
     *
     * @mbggenerated
     */
    public String getLastUpdateUser() {
        return lastUpdateUser;
    }

    public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity.last_update_user
     *
     * @param lastUpdateUser the value for pms_commodity.last_update_user
     *
     * @mbggenerated
     */
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser == null ? null : lastUpdateUser.trim();
    }

	/**
	 * @return the commodityCommentDomain
	 */
	public CommodityComment getCommodityCommentDomain() {
		return commodityCommentDomain;
	}

	/**
	 * @param commodityCommentDomain the commodityCommentDomain to set
	 */
	public void setCommodityCommentDomain(CommodityComment commodityCommentDomain) {
		this.commodityCommentDomain = commodityCommentDomain;
	}

	/**
	 * @return the taxRateName
	 */
	public String getTaxRateName() {
		return taxRateName;
	}

	/**
	 * @param taxRateName the taxRateName to set
	 */
	public void setTaxRateName(String taxRateName) {
		this.taxRateName = taxRateName;
	}

	/**
	 * @return the taxRateValue
	 */
	public String getTaxRateValue() {
		return taxRateValue;
	}

	/**
	 * @param taxRateValue the taxRateValue to set
	 */
	public void setTaxRateValue(String taxRateValue) {
		this.taxRateValue = taxRateValue;
	}
}