package com.spfood.pms.intf.domain;

import com.spfood.kernel.domain.DomainObject;

public class ProductItem implements DomainObject {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_item.composite_product_id
     *
     * @mbggenerated
     */
    private Long compositeProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_item.product_id
     *
     * @mbggenerated
     */
    private Long productId;


    private Product product;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_item.quantity
     *
     * @mbggenerated
     */
    private Integer quantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_item.composite_product_id
     *
     * @return the value of pms_product_item.composite_product_id
     *
     * @mbggenerated
     */
    public Long getCompositeProductId() {
        return compositeProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_item.composite_product_id
     *
     * @param compositeProductId the value for pms_product_item.composite_product_id
     *
     * @mbggenerated
     */
    public void setCompositeProductId(Long compositeProductId) {
        this.compositeProductId = compositeProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_item.product_id
     *
     * @return the value of pms_product_item.product_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_item.product_id
     *
     * @param productId the value for pms_product_item.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_item.quantity
     *
     * @return the value of pms_product_item.quantity
     *
     * @mbggenerated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_item.quantity
     *
     * @param quantity the value for pms_product_item.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }


	public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Override
	public String toString() {
		return "ProductItem [compositeProductId=" + compositeProductId
				+ ", productId=" + productId + ", product=" + product
				+ ", quantity=" + quantity + "]";
	}
}