package com.spfood.pms.intf.domain;

import com.spfood.kernel.domain.DomainObject;

public class RawMaterialsProperty implements DomainObject {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_raw_materials_property.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_raw_materials_property.raw_materials_code
     *
     * @mbggenerated
     */
    private String rawMaterialsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_raw_materials_property.raw_materials_property_name
     *
     * @mbggenerated
     */
    private String rawMaterialsPropertyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_raw_materials_property.raw_materials_property_value
     *
     * @mbggenerated
     */
    private String rawMaterialsPropertyValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_raw_materials_property.customer_define_flag
     *
     * @mbggenerated
     */
    private Integer customerDefineFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_raw_materials_property.id
     *
     * @return the value of pms_raw_materials_property.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_raw_materials_property.id
     *
     * @param id the value for pms_raw_materials_property.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_raw_materials_property.raw_materials_code
     *
     * @return the value of pms_raw_materials_property.raw_materials_code
     *
     * @mbggenerated
     */
    public String getRawMaterialsCode() {
        return rawMaterialsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_raw_materials_property.raw_materials_code
     *
     * @param rawMaterialsCode the value for pms_raw_materials_property.raw_materials_code
     *
     * @mbggenerated
     */
    public void setRawMaterialsCode(String rawMaterialsCode) {
        this.rawMaterialsCode = rawMaterialsCode == null ? null : rawMaterialsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_raw_materials_property.raw_materials_property_name
     *
     * @return the value of pms_raw_materials_property.raw_materials_property_name
     *
     * @mbggenerated
     */
    public String getRawMaterialsPropertyName() {
        return rawMaterialsPropertyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_raw_materials_property.raw_materials_property_name
     *
     * @param rawMaterialsPropertyName the value for pms_raw_materials_property.raw_materials_property_name
     *
     * @mbggenerated
     */
    public void setRawMaterialsPropertyName(String rawMaterialsPropertyName) {
        this.rawMaterialsPropertyName = rawMaterialsPropertyName == null ? null : rawMaterialsPropertyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_raw_materials_property.raw_materials_property_value
     *
     * @return the value of pms_raw_materials_property.raw_materials_property_value
     *
     * @mbggenerated
     */
    public String getRawMaterialsPropertyValue() {
        return rawMaterialsPropertyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_raw_materials_property.raw_materials_property_value
     *
     * @param rawMaterialsPropertyValue the value for pms_raw_materials_property.raw_materials_property_value
     *
     * @mbggenerated
     */
    public void setRawMaterialsPropertyValue(String rawMaterialsPropertyValue) {
        this.rawMaterialsPropertyValue = rawMaterialsPropertyValue == null ? null : rawMaterialsPropertyValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_raw_materials_property.customer_define_flag
     *
     * @return the value of pms_raw_materials_property.customer_define_flag
     *
     * @mbggenerated
     */
    public Integer getCustomerDefineFlag() {
        return customerDefineFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_raw_materials_property.customer_define_flag
     *
     * @param customerDefineFlag the value for pms_raw_materials_property.customer_define_flag
     *
     * @mbggenerated
     */
    public void setCustomerDefineFlag(Integer customerDefineFlag) {
        this.customerDefineFlag = customerDefineFlag;
    }
    public RawMaterialsProperty() {
    	super();
	}
    public RawMaterialsProperty(String code,String name,String value) {
    	super();
		this.rawMaterialsCode = code;
		this.rawMaterialsPropertyName = name;
		this.rawMaterialsPropertyValue = value;
	}
}