package com.spfood.pms.intf.domain;

import java.util.Date;

import com.spfood.kernel.domain.DomainObject;

public class PmsCommodityMsgTemp implements DomainObject {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity_msg_temp.commdity_code
     *
     * @mbggenerated
     */
    private String commdityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_commodity_msg_temp.pws_send_date
     *
     * @mbggenerated
     */
    private Date fmsSendDate;
    
    private int type;

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_commodity_msg_temp.commdity_code
     *
     * @return the value of pms_commodity_msg_temp.commdity_code
     *
     * @mbggenerated
     */
    public String getCommdityCode() {
        return commdityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_commodity_msg_temp.commdity_code
     *
     * @param commdityCode the value for pms_commodity_msg_temp.commdity_code
     *
     * @mbggenerated
     */
    public void setCommdityCode(String commdityCode) {
        this.commdityCode = commdityCode == null ? null : commdityCode.trim();
    }

	/**
	 * @return the type
	 */
	public int getType() {
		return type;
	}

	/**
	 * @param type the type to set
	 */
	public void setType(int type) {
		this.type = type;
	}

	/**
	 * @return the fmsSendDate
	 */
	public Date getFmsSendDate() {
		return fmsSendDate;
	}

	/**
	 * @param fmsSendDate the fmsSendDate to set
	 */
	public void setFmsSendDate(Date fmsSendDate) {
		this.fmsSendDate = fmsSendDate;
	}

}