package com.spfood.cms.intf.domain;

import javax.validation.constraints.Max;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.spfood.kernel.domain.DomainObject;

public class Advertisement implements DomainObject {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.slide_ads_pos_id
     *
     * @mbggenerated
     */
    @NotNull
    private Long slideAdsPosId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.imageUrl
     *
     * @mbggenerated
     */
    @NotNull
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.targetUrl
     *
     * @mbggenerated
     */
    @NotNull
    @Size(max=200,min=0)
    private String targetUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.displayOrder
     *
     * @mbggenerated
     */
    @NotNull
    @Max(value=100)
    private Integer displayOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.ID
     *
     * @return the value of advertisement.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.ID
     *
     * @param iD the value for advertisement.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.slide_ads_pos_id
     *
     * @return the value of advertisement.slide_ads_pos_id
     *
     * @mbggenerated
     */
    public Long getSlideAdsPosId() {
        return slideAdsPosId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.slide_ads_pos_id
     *
     * @param slideAdsPosId the value for advertisement.slide_ads_pos_id
     *
     * @mbggenerated
     */
    public void setSlideAdsPosId(Long slideAdsPosId) {
        this.slideAdsPosId = slideAdsPosId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.imageUrl
     *
     * @return the value of advertisement.imageUrl
     *
     * @mbggenerated
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.imageUrl
     *
     * @param imageUrl the value for advertisement.imageUrl
     *
     * @mbggenerated
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.targetUrl
     *
     * @return the value of advertisement.targetUrl
     *
     * @mbggenerated
     */
    public String getTargetUrl() {
        return targetUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.targetUrl
     *
     * @param targetUrl the value for advertisement.targetUrl
     *
     * @mbggenerated
     */
    public void setTargetUrl(String targetUrl) {
        this.targetUrl = targetUrl == null ? null : targetUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.displayOrder
     *
     * @return the value of advertisement.displayOrder
     *
     * @mbggenerated
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.displayOrder
     *
     * @param displayOrder the value for advertisement.displayOrder
     *
     * @mbggenerated
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }
}