package com.spfood.cms.intf.domain;

import java.util.List;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.Size;

import com.spfood.kernel.domain.DomainObject;

public class CatPromotePos implements DomainObject {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cat_promote_pos.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cat_promote_pos.category_name
     *
     * @mbggenerated
     */
    @Size(min=1,max=64)
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cat_promote_pos.image_url
     *
     * @mbggenerated
     */
    @Size(min=1,max=256)
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cat_promote_pos.display_order
     *
     * @mbggenerated
     */
    @Min(1)
    @Max(100)
    private Integer displayOrder;
    
    
    @Size(min=1,max=64)
    private String advert;
    
    private List<CatPromotedCommodity> catPromotedCommodityList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cat_promote_pos.ID
     *
     * @return the value of cat_promote_pos.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cat_promote_pos.ID
     *
     * @param iD the value for cat_promote_pos.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cat_promote_pos.category_name
     *
     * @return the value of cat_promote_pos.category_name
     *
     * @mbggenerated
     */
    public String getCategoryName() {
        return categoryName;
    }

    
    /**
     * @return the advert
     */
    public String getAdvert() {
        return advert;
    }

    /**
     * @param advert the advert to set
     */
    public void setAdvert(String advert) {
        this.advert = advert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cat_promote_pos.category_name
     *
     * @param categoryName the value for cat_promote_pos.category_name
     *
     * @mbggenerated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cat_promote_pos.image_url
     *
     * @return the value of cat_promote_pos.image_url
     *
     * @mbggenerated
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cat_promote_pos.image_url
     *
     * @param imageUrl the value for cat_promote_pos.image_url
     *
     * @mbggenerated
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cat_promote_pos.display_order
     *
     * @return the value of cat_promote_pos.display_order
     *
     * @mbggenerated
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cat_promote_pos.display_order
     *
     * @param displayOrder the value for cat_promote_pos.display_order
     *
     * @mbggenerated
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

	/**
	 * @return the catPromotedCommodityList
	 */
	public List<CatPromotedCommodity> getCatPromotedCommodityList() {
		return catPromotedCommodityList;
	}

	/**
	 * @param catPromotedCommodityList the catPromotedCommodityList to set
	 */
	public void setCatPromotedCommodityList(List<CatPromotedCommodity> catPromotedCommodityList) {
		this.catPromotedCommodityList = catPromotedCommodityList;
	}
}