package com.spfood.cms.intf.domain;

import java.util.List;

import com.spfood.kernel.domain.DomainObject;

public class CommodityPromotionPos implements DomainObject {
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_promotion_pos.id
     *
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_promotion_pos.name
     *
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_promotion_pos.max_slots
     *
     */
    private Integer maxSlots;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_promotion_pos.min_slots
     *
     */
    private Integer minSlots;
    
    private List<PromotedCommodity> promotedCommodityList;
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_promotion_pos.id
     *
     * @return the value of commodity_promotion_pos.id
     *
     */
    public Long getId() {
        return id;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_promotion_pos.id
     *
     * @param id the value for commodity_promotion_pos.id
     *
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_promotion_pos.name
     *
     * @return the value of commodity_promotion_pos.name
     *
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_promotion_pos.name
     *
     * @param name the value for commodity_promotion_pos.name
     *
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_promotion_pos.max_slots
     *
     * @return the value of commodity_promotion_pos.max_slots
     *
     */
    public Integer getMaxSlots() {
        return maxSlots;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_promotion_pos.max_slots
     *
     * @param maxSlots the value for commodity_promotion_pos.max_slots
     *
     */
    public void setMaxSlots(Integer maxSlots) {
        this.maxSlots = maxSlots;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_promotion_pos.min_slots
     *
     * @return the value of commodity_promotion_pos.min_slots
     *
     */
    public Integer getMinSlots() {
        return minSlots;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_promotion_pos.min_slots
     *
     * @param minSlots the value for commodity_promotion_pos.min_slots
     *
     * @mbggenerated
     */
    public void setMinSlots(Integer minSlots) {
        this.minSlots = minSlots;
    }


    /**
     * @return the promotedCommodityList
     */
    public List<PromotedCommodity> getPromotedCommodityList() {
        return promotedCommodityList;
    }


    /**
     * @param promotedCommodityList the promotedCommodityList to set
     */
    public void setPromotedCommodityList(
            List<PromotedCommodity> promotedCommodityList) {
        this.promotedCommodityList = promotedCommodityList;
    }


    
}