package com.spfood.pms.search.intf.domain;

import com.spfood.kernel.domain.DomainObject;

public class ProductPicture implements DomainObject {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_picture.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_picture.product_code
     *
     * @mbggenerated
     */
    private String productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_picture.picture_address
     *
     * @mbggenerated
     */
    private String pictureAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_picture.picture_show_position
     *
     * @mbggenerated
     */
    private Integer pictureShowPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_picture.picture_show_order
     *
     * @mbggenerated
     */
    private Integer pictureShowOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_picture.picture_size
     *
     * @mbggenerated
     */
    private String pictureSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_picture.picture_property
     *
     * @mbggenerated
     */
    private String pictureProperty;

    public ProductPicture() {
		super();
		// TODO Auto-generated constructor stub
	}

	public ProductPicture(String productCode, String pictureAddress) {
		super();
		this.productCode = productCode;
		this.pictureAddress = pictureAddress;
		}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_picture.id
     *
     * @return the value of pms_product_picture.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_picture.id
     *
     * @param id the value for pms_product_picture.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_picture.product_code
     *
     * @return the value of pms_product_picture.product_code
     *
     * @mbggenerated
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_picture.product_code
     *
     * @param productCode the value for pms_product_picture.product_code
     *
     * @mbggenerated
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_picture.picture_address
     *
     * @return the value of pms_product_picture.picture_address
     *
     * @mbggenerated
     */
    public String getPictureAddress() {
        return pictureAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_picture.picture_address
     *
     * @param pictureAddress the value for pms_product_picture.picture_address
     *
     * @mbggenerated
     */
    public void setPictureAddress(String pictureAddress) {
        this.pictureAddress = pictureAddress == null ? null : pictureAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_picture.picture_show_position
     *
     * @return the value of pms_product_picture.picture_show_position
     *
     * @mbggenerated
     */
    public Integer getPictureShowPosition() {
        return pictureShowPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_picture.picture_show_position
     *
     * @param pictureShowPosition the value for pms_product_picture.picture_show_position
     *
     * @mbggenerated
     */
    public void setPictureShowPosition(Integer pictureShowPosition) {
        this.pictureShowPosition = pictureShowPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_picture.picture_show_order
     *
     * @return the value of pms_product_picture.picture_show_order
     *
     * @mbggenerated
     */
    public Integer getPictureShowOrder() {
        return pictureShowOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_picture.picture_show_order
     *
     * @param pictureShowOrder the value for pms_product_picture.picture_show_order
     *
     * @mbggenerated
     */
    public void setPictureShowOrder(Integer pictureShowOrder) {
        this.pictureShowOrder = pictureShowOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_picture.picture_size
     *
     * @return the value of pms_product_picture.picture_size
     *
     * @mbggenerated
     */
    public String getPictureSize() {
        return pictureSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_picture.picture_size
     *
     * @param pictureSize the value for pms_product_picture.picture_size
     *
     * @mbggenerated
     */
    public void setPictureSize(String pictureSize) {
        this.pictureSize = pictureSize == null ? null : pictureSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_picture.picture_property
     *
     * @return the value of pms_product_picture.picture_property
     *
     * @mbggenerated
     */
    public String getPictureProperty() {
        return pictureProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_picture.picture_property
     *
     * @param pictureProperty the value for pms_product_picture.picture_property
     *
     * @mbggenerated
     */
    public void setPictureProperty(String pictureProperty) {
        this.pictureProperty = pictureProperty == null ? null : pictureProperty.trim();
    }

	@Override
	public String toString() {
		return "ProductPicture [id=" + id + ", productCode=" + productCode
				+ ", pictureAddress=" + pictureAddress
				+ ", pictureShowPosition=" + pictureShowPosition
				+ ", pictureShowOrder=" + pictureShowOrder + ", pictureSize="
				+ pictureSize + ", pictureProperty=" + pictureProperty + "]";
	}
}